version: '3'

networks:
  app:
    driver: bridge
  nginx-proxy:
    external: true
services:
    app:
        build:
          context: .
          dockerfile: docker/app/Dockerfile
          args:
            - ENV_FILE=.env.dev
        image: ${APP_IMAGE}
        container_name: richy-casino-front-app
        restart: ${DK_RESTART}
        logging:
          driver: 'json-file'
          options:
            max-file: '5'
            max-size: '100m'
        networks:
          - app
    nginx:
        build:
          context: .
          dockerfile: docker/nginx/Dockerfile
          args:
            - APP_IMAGE=${APP_IMAGE}
        image: ${NGINX_IMAGE}
        container_name: richy-casino-front-nginx
        logging:
          driver: 'json-file'
          options:
            max-file: '5'
            max-size: '100m'
        restart: ${DK_RESTART}
        networks:
          - app
          - nginx-proxy
        depends_on:
          - app
        environment:
          API_HOST: http://richy-casino-api-nginx
          ADMIN_HOST: http://richy-casino-admin
          VIRTUAL_HOST: richy-casino.dev.glob-com.ru
          LETSENCRYPT_HOST: richy-casino.dev.glob-com.ru
          LETSENCRYPT_EMAIL: sites.globcom@yandex.ru
          VIRTUAL_PORT: 80
    nginx_rc:
      build:
        context: .
        dockerfile: docker/nginx/Dockerfile
        args:
          - APP_IMAGE=${APP_IMAGE}
      image: ${NGINX_IMAGE}
      container_name: richy-casino-front-nginx-rc
      logging:
        driver: 'json-file'
        options:
          max-file: '5'
          max-size: '100m'
      restart: ${DK_RESTART}
      networks:
        - app
        - nginx-proxy
      depends_on:
        - app
      environment:
        API_HOST: http://richy-casino-api-nginx
        ADMIN_HOST: http://richy-casino-admin
        VIRTUAL_HOST: rch-testdemoweb.com
        SSL: "1"
        VIRTUAL_PORT: 80
